import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button } from '../components/button/button.component';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hilanga App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Button type="primary">Button 1</Button>
        </div>
        <div className={styles.grid}>
          <Button type="secondary">Button 1</Button>
        </div>
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
};

export default Home;
